export const AuthConstants = {
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_ERROR: 'SIGNIN_ERROR',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR'
}

export const ProfileConstants = {
  MODIFY_USERINFO_SUCCESS: 'MODIFY_USERINFO_SUCCESS',
  MODIFY_USERINFO_ERROR: 'MODIFY_USERINFO_ERROR',
  CLOSE_MODAL: 'CLOSE_MODAL',
  PASSWORDS_ARE_NOT_EQUAL: 'PASSWORDS_ARE_NOT_EQUAL',
  MODIFY_USERCREDS_SUCCESS: 'MODIFY_USERCREDS_SUCCESS',
  MODIFY_USERCREDS_ERROR: 'MODIFY_USERCREDS_ERROR',
  CHANGE_PROFILE_IMAGE_SUCCESS: 'CHANGE_PROFILE_IMAGE_SUCCESS',
  CHANGE_PROFILE_IMAGE_ERROR: 'CHANGE_PROFILE_IMAGE_ERROR'
}

export const ChatConstants = {
  MESSAGE_SEND_SUCCESS: 'MESSAGE_SEND_SUCCESS',
  MESSAGE_SEND_ERROR: 'MESSAGE_SEND_ERROR',
  CLOSE_MODAL: 'CLOSE_MODAL',
  SUBSCRIBED_MESSAGES_ADDED: 'SUBSCRIBED_MESSAGES_ADDED',
  STORE_SUBSCRIPTION_HANDLE: 'STORE_SUBSCRIPTION_HANDLE',
  CANCEL_SUBSCRIPTION: 'CANCEL_SUBSCRIPTION',
  TRIGGER_BATCH_LOADING_FLAG: 'TRIGGER_BATCH_LOADING_FLAG',
  LOAD_MORE_SUCCESSED: 'LOAD_MORE_SUCCESSED',
  LOAD_MORE_FAILED: 'LOAD_MORE_FAILED',
  OPEN_USER_INFO_MODAL: 'OPEN_USER_INFO_MODAL',
  USER_INFO_LOADED: 'USER_INFO_LOADED',
  USER_INFO_LOAD_FAILED: 'USER_INFO_LOAD_FAILED',
  CLOSE_USER_INFO_MODAL: 'CLOSE_USER_INFO_MODAL'
}
