export const AuthConstants = {
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_ERROR: 'SIGNIN_ERROR',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR'
}

export const ProfileConstants = {
  MODIFY_USERINFO_SUCCESS: 'MODIFY_USERINFO_SUCCESS',
  MODIFY_USERINFO_ERROR: 'MODIFY_USERINFO_ERROR',
  CLOSE_MODAL: 'CLOSE_MODAL',
  PASSWORDS_ARE_NOT_EQUAL: 'PASSWORDS_ARE_NOT_EQUAL',
  MODIFY_USERCREDS_SUCCESS: 'MODIFY_USERCREDS_SUCCESS',
  MODIFY_USERCREDS_ERROR: 'MODIFY_USERCREDS_ERROR'
}
